export const PRODUCTS = [
    {
        _id: 1,
        name: 'Product Name',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p1.png',
    },
    {
        _id: 2,
        name: 'Product Name',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p2.png',
    },
    {
        _id: 3,
        name: 'Product Name',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p3.png',
    },
    {
        _id: 4,
        name: 'Product Name',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p4.png',
    },
    {
        _id: 5,
        name: 'Product Name',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p5.png',
    },
    {
        _id: 6,
        name: 'Product Name',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p6.png',
    },
    {
        _id: 7,
        name: 'Product Name',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p8.png',
    },
    {
        _id: 9,
        name: 'Product Name',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p9.png',
    },
    {
        _id: 10,
        name: 'Product Name',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p10.png',
    },
    {
        _id: 11,
        name: 'Product Name',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p11.png',
    },
    {
        _id: 12,
        name: 'Product Name',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p12.png',
    },
]
