export const PRODUCTS = [
    {
        _id: 1,
        name: 'Product 1',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p1.png',
    },
    {
        _id: 2,
        name: 'Product 2',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p2.png',
    },
    {
        _id: 3,
        name: 'Product 3',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p3.png',
    },
    {
        _id: 4,
        name: 'Product 4',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p4.png',
    },
    {
        _id: 5,
        name: 'Product 5',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p5.png',
    },
    {
        _id: 6,
        name: 'Product 6',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p6.png',
    },
    {
        _id: 7,
        name: 'Product 7',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p7.png',
    },
    {
        _id: 8,
        name: 'Product 8',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p8.png',
    },
    {
      _id: 9,
      name: 'Product 9',
      description: 'Product Description',
      summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      price: 99,
      image: 'p9.png',
  },
    {
        _id: 10,
        name: 'Product 10',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p10.png',
    },
    {
        _id: 11,
        name: 'Product 11',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p11.png',
    },
    {
        _id: 12,
        name: 'Product 12',
        description: 'Product Description',
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: 99,
        image: 'p12.png',
    },
]
